ALTER TABLE usuario ADD COLUMN razao_social VARCHAR(255);
ALTER TABLE usuario ADD COLUMN cnpj VARCHAR(20);
ALTER TABLE usuario ADD COLUMN cpf VARCHAR(14);
ALTER TABLE usuario ADD COLUMN email_authsoft VARCHAR(255);
