ALTER TABLE cliente ADD COLUMN bairro VARCHAR(255);
ALTER TABLE cliente ADD COLUMN numero VARCHAR(20);
ALTER TABLE cliente ADD COLUMN complemento VARCHAR(255);
ALTER TABLE cliente ADD COLUMN pais VARCHAR(100);
