ALTER TABLE audit_log 
ADD COLUMN IF NOT EXISTS dados_anteriores TEXT,
ADD COLUMN IF NOT EXISTS dados_novos TEXT,
ADD COLUMN IF NOT EXISTS usuario_nome VARCHAR(255),
ADD COLUMN IF NOT EXISTS ip_origem VARCHAR(255);

ALTER TABLE audit_log DROP COLUMN IF EXISTS detalhes;
